In [1]:
#convert list to ndarray
import numpy as np
x = [1,2,3]
a = np.asarray(x)
print( a )

[1 2 3]


In [2]:
# dtype is set
import numpy as np
x = [1,2,3]
a = np.asarray(x,dtype=float)
print( a )

[1. 2. 3.]


In [3]:
#ndarray from tuple
import numpy as np
x = (1,2,3)
a = np.asarray(x)
print( a )

[1 2 3]


In [4]:
#ndarray from list of tuples
import numpy as np
x = [(1,2,3),(4,5)]
a = np.asarray(x)
print( a )

[(1, 2, 3) (4, 5)]


In [6]:
#from buffer function
import numpy as np
s = 'Hello World'
a = np.frombuffer(s,dtype='S1')
print( a ) 

SyntaxError: invalid syntax (<ipython-input-6-36a8f4ddd695>, line 3)

In [7]:
#create list object using range function
import numpy as np
list = range(5)
print( list )

range(0, 5)


In [8]:
# obtain iterator object from list
import numpy as np
list = range(5)
it = iter(list)

#use iterator to create adarray
print( x )

[(1, 2, 3), (4, 5)]


In [9]:
# numpy
import numpy as np
x = np.arange(5)
print( x )

[0 1 2 3 4]


In [10]:
#example 2
import numpy as np

#dtype set
x = np.arange(5,dtype=float)
print( x )

[0. 1. 2. 3. 4.]


In [11]:
# start and stop parameters set
import numpy as np
x = np.arange(10,20,2)
print( x )

[10 12 14 16 18]


In [13]:
#Example 4
import numpy as np
x = np.linspace(10,20,5)
print( x )

[10.  12.5 15.  17.5 20. ]


In [14]:
#endpoint set to false
import numpy as np
x = np.linspace(10,20,5,endpoint=False)
print( x )

[10. 12. 14. 16. 18.]


In [15]:
#find retstep value
import numpy as np
x = np.linspace(1,2,5,retstep=True)
print( x )

#retstep here is 0.25

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [16]:
# logspace
import numpy as np
a = np.logspace(1.0,2.0,num=10)
print( a )

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [17]:
# set base of log space to 2
import numpy as np
a = np.logspace(1,10,num=10,base=2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [18]:
#Example 1
import numpy as np
a = np.arange(10)
s = slice(2,7,2)
print( a[s] )

[2 4 6]


In [19]:
#example 2 
import numpy as np
a = np.arange(10)
b = a[2:7:2]
print( b )

[2 4 6]


In [20]:
# Slice single item
import numpy as np
a = np.arange(10)
b = a[5]
print( b )

5


In [23]:
#slice items starting from index
import numpy as np
print( a[5:7] )

[5 6]


In [24]:
# Example 6
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,7]])
print( a )

#slice item starting from index

[[1 2 3]
 [3 4 5]
 [4 5 7]]


In [27]:
# array to begin with
import numpy as np
a = np.array([[1,2,3],[4,5,6],[6,7,9]])
print( 'Our array is:')
print( a )
print ('\n')

#this retures array of items in the second column
print ('The items in the second column are:')
print (a[...,1])
print ('\n')

# Now we will slice all item from the second row
print('The items in the second row are:')
print(a[1,...])
print('\n')

#Now we will slice all items from column 1 onwards
print('The items column1 onwards are:')
print(a[...,1:])



Our array is:
[[1 2 3]
 [4 5 6]
 [6 7 9]]


The items in the second column are:
[2 5 7]


The items in the second row are:
[4 5 6]


The items column1 onwards are:
[[2 3]
 [5 6]
 [7 9]]


In [28]:
#Example 1
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [30]:
#exampel 2
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is:')
print(x)
print('\n')
rows = np.array([0,0],[3,3])
cols = np.array([[0,2][0,2]])
y = x[rows,cols]
print('The corner elements of this array are:')
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


TypeError: data type not understood

In [31]:
# Example numpy 
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is:')
print(x)
print('\n')

#Now we will print the items greater then 5
print('The items greater then 5 are:')
print(x[x>5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater then 5 are:
[ 6  7  8  9 10 11]


In [32]:
# Example 5
import numpy as np
a = np.array([np.nan,1,2,np.nan,3,4,5])

print( a[~np.isnan(a)] )

[1. 2. 3. 4. 5.]


In [33]:
# Example 6
#The following example shows how to
a = np.array([1+2+6j,5,3.5+5j])

print( a[np.iscomplex(a)] )

[3. +6.j 3.5+5.j]
