In [2]:
#Multiply
import numpy as np
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c= a*b
print( c )

[ 10  40  90 160]


In [3]:
#Broadcasting
import numpy as np
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],
             [20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print('First array:')
print( a )
print('\n')

print('Second array:')
print(b)
print('\n')

print('First array + Second array')
print(a+b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First array + Second array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [2]:
#Example 6
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a,flags=['external_loop'],order='F'):
    print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]
