In [1]:
import numpy as np
x = np.array([[1], [2], [3]]) y = np.array([4, 5, 6])
# tobroadcast x against y b = np.broadcast(x,y)
# it has an iterator property, a tuple of iterators along self's "components." print 'Broadcast x against y:'
r,c = b.iters
print r.next(), c.next()
print r.next(), c.next() print '\n'
# shape attribute returns the shape of broadcast object print 'The shape of the broadcast object:'
print b.shape
print '\n'
# to add x and y manually using broadcast
b = np.broadcast(x,y)
c = np.empty(b.shape)
print 'Add x and y manually using broadcast:' print c.shape
print '\n'
c.flat = [u+v for (u,v) in b]
print 'After applying the flat function:' print c
print '\n'
# same result obtained by NumPy's built-in broadcasting support print 'The summation of x and y:'
print x+y

SyntaxError: invalid syntax (<ipython-input-1-3f294ca95400>, line 2)

In [2]:
#Example 10
import numpy as np
a = np.arange(4).reshape(1,4)
print('The original array:')
print(a)
print('\n')

print('After applying the broadcast_to function:')
print(np.broadcast_to(a,(4,4)))

The original array:
[[0 1 2 3]]


After applying the broadcast_to function:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [3]:
# numpy.expand_dims
import numpy as np
x = np.array(([1,2],[3,4]))
print('Aray x:')
print(x)
print('\n')

y = np.expand_dims(x,axis=0)
print('Array y:')
print(y)
print('\n')

Aray x:
[[1 2]
 [3 4]]


Array y:
[[[1 2]
  [3 4]]]




In [4]:
# Expands Dims
import numpy as np
print('Array x:')
print(x)
print('\n')

y = np.expand_dims(x,axis=0)
print('Array y:')
print(y)
print('\n')

print('The shape of X and Y array:')
print( x.shape,y.shape )
print('\n')

#insert axis at position 1
y = np.expand_dims(x,axis=1)
print('Array Y after inserting axis at position 1:')
print(y)
print('\n')

print('x.ndim and y.ndim:')
print(x.ndim,y.ndim)
print('\n')

print('x.shape and y.shape:')
print(x.shape,y.shape)

Array x:
[[1 2]
 [3 4]]


Array y:
[[[1 2]
  [3 4]]]


The shape of X and Y array:
(2, 2) (1, 2, 2)


Array Y after inserting axis at position 1:
[[[1 2]]

 [[3 4]]]


x.ndim and y.ndim:
2 3


x.shape and y.shape:
(2, 2) (2, 1, 2)


In [5]:
#numpy.squeeze
import numpy as np
x = np.arange(9).reshape(1,3,3)
print('Array X:')
print(x)
print('\n')

y = np.squeeze(x)
print('Array Y:')
print(y)
print('\n')

print('The shapes of  X and Y array:')
print( x.shape,y.shape )

Array X:
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


Array Y:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


The shapes of  X and Y array:
(1, 3, 3) (3, 3)


In [6]:
# numpy.concatenate
import numpy as np
a = np.array([[1,2],[3,4]])
print('first array:')
print(a)
print('\n')

b = np.array([[5,6],[7,8]])
print('second Array:')
print(b)
print('\n')

#both the arrays are of seme dimensions
print('Joining the two array along axis 0:')
print( np.concatenate((a,b)) )
print('\n')

print('Joining the two array along axis 1:')
print( np.concatenate((a,b),axis=1) )

first array:
[[1 2]
 [3 4]]


second Array:
[[5 6]
 [7 8]]


Joining the two array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [8]:
#numpy.stack
import numpy as np
a = np.array([[1,2],[3,4]])
print('First Array:')
print(a)
print('\n')

b = np.array([[5,6],[7,8]])
print('Second Array:')
print(b)
print('\n')

print('Stack the two arrays along axis 0:')
print( np.stack((a,b),0) )
print('\n')

print('Stack the two arrays along axis 1:')
print( np.stack((a,b),1) )

First Array:
[[1 2]
 [3 4]]


Second Array:
[[5 6]
 [7 8]]


Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [9]:
# numpy.hstack and numpy.vstack
import numpy as np
a = np.array([[1,2],[3,4]])
print('First array:')
print(a)
print('\n')

b = np.array([[5,6],[7,8]])
print('Second array:')
print(b)
print('\n')

print('Horizontal stacking:')
c = np.hstack((a,b))
print(c)

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]


In [10]:
# numpy.split
import numpy as np
a = np.arange(9)
print('First array:')
print(a)
print('\n')

print('splite the array in 3 equal sized subarrays:')
b = np.split(a,3)
print(b)
print('\n')

print('Split the array at positions indicated in a-D array:')
b = np.split(a,[4,7])
print(b)

First array:
[0 1 2 3 4 5 6 7 8]


splite the array in 3 equal sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Split the array at positions indicated in a-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [12]:
# numpy.hsplit and numpy.vsplit
import numpy as np
a = np.arange(16).reshape(4,4)
print('First array:')
print(a)
print('\n')

print('Horizontal splitting:')
b = np.hsplit(a,2)
print(b)
print('\n')

print('Vertical splitting:')
b = np.vsplit(a,2)
print(b )

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [13]:
# numpy.resize
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print('First array:')
print(a)
print('\n')

print('The shape of first array:')
print( a.shape )
print('\n')

b = np.resize(a,(3,2))
print('Second array:')
print(b)
print('\n')

print('The Shape of second array:')
print( b.shape )
print('\n')

# Observe that first row of a is repeated in b since size is bigger
print('Resize the second array:')
b = np.resize(a,(3,3))
print(b)

First array:
[[1 2 3]
 [4 5 6]]


The shape of first array:
(2, 3)


Second array:
[[1 2]
 [3 4]
 [5 6]]


The Shape of second array:
(3, 2)


Resize the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [16]:
# numpy.append
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print('First array:')
print(a)
print('\n')

print('Append elements to array:')
print( np.append(a,[7,8,9]) )
print('\n')

print('Append elements along axis 0:')
print( np.append(a,[[7,8,9]],axis=0) )
print('\n')

print('Append elements along axis 1:')
print( np.append(a,[[5,5,5],[7,8,9]],axis=1) )

First array:
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
