In [1]:
#numpy.char.strip()
import numpy as np
print( np.char.strip('ashok arora','a') )
print( np.char.strip(['arora','admin','java'],'a') )

shok aror
['ror' 'dmin' 'jav']


In [2]:
#numpy.char.join()
import numpy as np
print( np.char.join(':','dmy') )
print( np.char.join([':','-'],['dmy','ymd']) )

d:m:y
['d:m:y' 'y-m-d']


In [3]:
#numpy.char.replace()
import numpy as np
print( np.char.replace('He is a good boy','is','was') )

He was a good boy


In [4]:
#numpy.char.encode()
import numpy as np
a = np.char.encode('hello','cp500')
print( a )
print( np.char.decode(a,'cp500') )

b'\x88\x85\x93\x93\x96'
hello


In [6]:
# Trigonometric Functions
import numpy as np
a = np.array([0,30,45,60,90])
print('Sine of different angles:')

#Convert to radians by multiplying with ip/180
print( np.sin(a*np.pi/180) )
print('\n')

print('cosine values for angles in array:')
print( np.cos(a*np.pi/180) )
print('\n')

print('Tangent value for given angles:')
print( np.tan(a*np.pi/180) )

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent value for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [7]:
#numpy.degrees()
import numpy as np

a = np.array([0,30,45,60,90])
sin=np.sin(a*np.pi/100)
print( sin )
print('\n')

print('Compute sine inverse of angle. Returned values are in radians.')
inv=np.arcsin(sin)
print(inv)
print('\n')

print('Check result by converting to degres:')
print( np.degrees(inv) )
print('\n')

print('arccos and arctan function behave similarly:')
cos=np.cos(a*np.pi/180)
print(cos)
print('\n')

print('Inverse of cos:')
inv=np.arccos(cos)
print(inv)
print('\n')

print('In degrees:')
print( np.degrees(inv) )
print('\n')

print('Tan function:')
tan=np.tan(a*np.pi/180)
print(tan)
print('\n')

print('Inverse of tan:')
inv =np.arctan(tan)
print(inv)
print('\n')

print('In degrees:')
print( np.degrees(inv) )

[0.         0.80901699 0.98768834 0.95105652 0.30901699]


Compute sine inverse of angle. Returned values are in radians.
[0.         0.9424778  1.41371669 1.25663706 0.31415927]


Check result by converting to degres:
[ 0. 54. 81. 72. 18.]


arccos and arctan function behave similarly:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Inverse of cos:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In degrees:
[ 0. 30. 45. 60. 90.]


Tan function:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Inverse of tan:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In degrees:
[ 0. 30. 45. 60. 90.]


In [8]:
#numpy.around()
import numpy as np
a = np.array([1.0,5.55,123,0.567,25.532])
print('Original array:')
print(a)
print('\n')

print('After rounding:')
print( np.around(a) )
print( np.around(a,decimals=1) )
print( np.around(a,decimals=-1) )

Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [9]:
#Numpy.floor()
import numpy as np
a = np.array([-1.7,1.5,0.6,10])
print('The given array:')
print(a)
print('\n')

#
print('The modified array:')
print( np.floor(a) )

The given array:
[-1.7  1.5  0.6 10. ]


The modified array:
[-2.  1.  0. 10.]


In [10]:
#numpy.ceil()
import numpy as np
a = np.array([-1.7,1.5,-0.2,0.6,10])
print('The given array:')
print(a)
print('\n')

print('The modified array:')
print( np.ceil(a) )

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-1.  2. -0.  1. 10.]
