In [1]:
#numpy.around()
import numpy as np
a = np.array([1.0,5.55,123,0.567,25.532])

print('Original array:')
print(a)
print('\n')

print('After rounding:')
print( np.around(a) )
print( np.around(a,decimals=1) )
print( np.around(a,decimals=-1) )

Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [2]:
#numpy.floor()
import numpy as np
a = np.array([-1.7,1.5,-0.2,-0.6,10])

print('The given array:')
print(a)
print('\n')

print('The modified array:')
print( np.floor(a) )

The given array:
[-1.7  1.5 -0.2 -0.6 10. ]


The modified array:
[-2.  1. -1. -1. 10.]


In [3]:
#numpy.ceil()
import numpy as np
a = np.array([-1.7,1.5,-0.2,0.6,10])

print('The given array:')
print(a)
print('\n')

print('The modified array:')
print( np.ceil(a) )

The given array:
[-1.7  1.5 -0.2  0.6 10. ]


The modified array:
[-1.  2. -0.  1. 10.]
