In [7]:
#Example 1
import numpy as np
a = np.arange(9)
print('The original array:')
print(a)
print('\n')

b = a.reshape(3,3)
print('The modified array:')
print(b)

The original array:
[0 1 2 3 4 5 6 7 8]


The modified array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#Example 2
import numpy as np

a = np.arange(8).reshape(2,4)
print('The original array:')
print (a)
print('\n')
print('After applying the flat function:')

#Returns element corresponding to index in flattened array
print( a.flat[5] )

The original array:
[[0 1 2 3]
 [4 5 6 7]]


After applying the flat function:
5


In [12]:
#Example 3
import numpy as np

a = np.arange(8).reshape(2,4)
print('The original array is:')
print(a)
print('\n')

#Default is column-major
print('The flattened array is:')
print(a.flatten())
print('\n')

print('The flattended array in F-style ordering:')
print( a.flatten(order='F'))

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


The flattened array is:
[0 1 2 3 4 5 6 7]


The flattended array in F-style ordering:
[0 4 1 5 2 6 3 7]
