In [2]:
#Example 5
import numpy as np
a = np.arange(12).reshape(3,4)
print('The original array is:')
print(a)


print('\n')
print('The transposed array is:')
print ( np.transpose(a) )

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
