In [2]:
import numpy as np

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:')
print(a)
print('\n')

print('Applying mean() function:')
print( np.mean(a) )
print('\n')

print('Applying mean() function along axis 0:')
print( np.mean(a,axis=0) )
print('\n')

print('Applying mean() function along axis 0:')
print( np.mean(a,axis=1) )

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function:
3.6666666666666665


Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


Applying mean() function along axis 0:
[2. 4. 5.]


In [3]:
#numpy.average()
import numpy as np

a = np.array([1,2,3,4])
print('Our array is:')
print(a)
print('\n')

print('Applying average() function:')
print(np.average(a))
print('\n')

#This is same as when weight is not specified
wts = np.array([4,3,2,1])
print('Applying average() function again:')
print( np.average(a,weights=wts) )
print('\n')

#Resturent the sum of weights, if is returned peramenters is set to True.
print('Sum of weights')
print( np.average([1,2,3,4],weights=[4,3,2,1],returned=True) )

Our array is:
[1 2 3 4]


Applying average() function:
2.5


Applying average() function again:
2.0


Sum of weights
(2.0, 10.0)


In [5]:
#Example
import numpy as np

a = np.arange(6).reshape(3,2)
print('Our array is:')
print(a)
print('\n')

print('Modified array:')
wt=np.array([3,5])
print( np.average(a,axis=1,weights=wt) )
print('\n')

print('Modified array:')
print( np.average(a,axis=1,weights=wt,returned=True) )

Our array is:
[[0 1]
 [2 3]
 [4 5]]


Modified array:
[0.625 2.625 4.625]


Modified array:
(array([0.625, 2.625, 4.625]), array([8., 8., 8.]))


In [6]:
#Standard Deviation
import numpy as np
print( np.var([1,2,3,4]) )

1.25
