In [1]:
# It Creates 2 dimensional adarray
import numpy as np
a = np.arange(8).reshape(2,2,2)
print('The original array:')
print(a)
print('\n')

#to roll axis 2 to axis-0 ( along width to along depth)
print('After applying rollaxis function:')
print(np.rollaxis(a,2))

# to roll axis 0 to 1 ( along width to height )
print('\n')
print('After applying rollaxis function:')
print( np.rollaxis(a,2,1) )

The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


After applying rollaxis function:
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


After applying rollaxis function:
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
