In [2]:
import tensorflow as tf

In [3]:
sess = tf.compat.v1.InteractiveSession()

In [4]:
my_tensor = tf.random.uniform((5,5),0,2)

In [7]:
var1 = tf.Variable(initial_value=my_tensor)

In [17]:
#sess.run(var1)
init = tf.compat.v1.global_variables_initializer()


In [19]:
tf.print(var1)

[[1.41438818 1.84634686 1.82944798 0.658118248 1.57806969]
 [0.690398216 1.23628473 0.264030218 0.974745512 0.764630079]
 [0.824514627 0.787634611 0.823812 0.498203754 1.53607988]
 [1.17801762 1.04195833 1.70195413 1.17534041 0.54575181]
 [0.0379309654 1.04011512 1.42431426 0.721550465 1.84857392]]


In [28]:
#place holder
pH = tf.compat.v1.placeholder(tf.float32)

RuntimeError: tf.placeholder() is not compatible with eager execution.