In [1]:
#Example 1
import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a*b

print(c)

[ 10  40  90 160]


In [2]:
#Example 2
import numpy as np
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],
             [20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print('First array:')
print(a)
print('\n')

print('Second array')
print(b)
print('\n')

print('First Array + Second Array')
print(a+b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
