In [4]:
#Example 1
#Integer Indexing
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,0,1]]
print(y)

[1 3 6]


In [6]:
#Example 2
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

print('Our array is:')
print(x)
print('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]

print('The corner elements of this array are:')
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [8]:
#Boolearn Array Indexing
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

print('Our array is:')
print(x)
print('\n')

#Now we will print the items greater than 5
print('The items greater then 5 are:')
print( x[x<5] )

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater then 5 are:
[0 1 2 3 4]


In [14]:
#Example 5
import numpy as np
a = np.array([np.nan,1,2,np.nan,3,4,5])
print( a[~np.isnan(a)] )

[1. 2. 3. 4. 5.]


In [22]:
#Example 6
import numpy as np
a = np.array([1,2+6j,5,3.5+5j])
print( a[np.iscomplex(a)] )

[2. +6.j 3.5+5.j]
