In [1]:
#ndarray.shape
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print( a.shape )

(2, 3)


In [2]:
# this resizes the ndarray
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
#Example
#NumPy also provides a reshape function to resize an array.
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#ndarray.ndim
#an array of evenly spaced numbers
import numpy as np
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [21]:
#Example 5
# this is one dimensional array
import numpy as np
a = np.arange(24)
a.ndim


# now reshape it
b = a.reshape(2,4,3)
print(b)
#b is having three dimensions

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [22]:
#dtype of array is int8 ( 1 byte )
import numpy as np
x = np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

1


In [29]:
#Example 7
import numpy as np
x = np.array([1,2,3,4,5,6,7,9],dtype=np.float64)
print(x.itemsize)

8
