In [4]:
#numpy.reshape
import numpy as np
a = np.arange(16)

print('The original array:')
print(a)
print('\n')

b = a.reshape(4,4)
print('The modified array:')
print(b)

The original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


The modified array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
#numpy.ndarray.flat
import numpy as np
a = np.arange(8).reshape(2,4)


print('the original array:')
print(a)
print('\n')

print('After applying the flat function:')

#Returns element correspondin the index in flatted array
print( a.flat[5] )

the original array:
[[0 1 2 3]
 [4 5 6 7]]


After applying the flat function:
5


In [8]:
#numpy.ndarray.flatten
import numpy as np
a = np.arange(8).reshape(2,4)

print('The original array is:')
print(a)
print('\n')

#default is column-major
print('the flattened array is:')
print(a.flatten())
print('\n')

print('The flattened array is f-style ordering:')
print( a.flatten(order='F') )

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


the flattened array is:
[0 1 2 3 4 5 6 7]


The flattened array is f-style ordering:
[0 4 1 5 2 6 3 7]


In [9]:
#numpy.raval
import numpy as np

a = np.arange(8).reshape(2,4)

print('The original array is:')
print(a)

print('\n')
print('The transposed array is:')
print( np.transpose(a) )

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


The transposed array is:
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [10]:
#numpy.ndarray.T
import numpy as np
a = np.arange(12).reshape(3,4)


print('The original array is:')
print(a)
print('\n')

print('Array after applying the function:')
print(a.T)

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array after applying the function:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
