In [2]:
#matlib.empty()
import numpy.matlib
import numpy as np
print( np.matlib.empty((2,2)) )

#filled with random data

[[1.69759663e-313 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [3]:
#numpy.matlib.zeros()
import numpy.matlib
import numpy as np

print(np.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [6]:
#numpy.matlib.ones()
import numpy.matlib
import numpy as np
print( np.matlib.ones((9,9)) )

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [13]:
#numpy.matlib.eye()
import numpy.matlib
import numpy as np
print( np.matlib.eye(n=5,M=10,k=2,dtype=float) )

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [14]:
#numpy.matlib.identity()
import numpy.matlib
import numpy as np

print(np.matlib.identity(5,dtype=float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
#numpy.matlib.rand()
import numpy.matlib
import numpy as np

print( np.matlib.rand(3,3) )

[[0.15371725 0.48946504 0.57163167]
 [0.08854389 0.68694743 0.64503742]
 [0.75608592 0.62159247 0.21707232]]


In [16]:
#Example
import numpy.matlib
import numpy as np

i=np.matrix('1,2;3,4')
print(i)

[[1 2]
 [3 4]]


In [17]:
#example
import numpy.matlib
import numpy as np

j = np.asarray(i)
print(j)

[[1 2]
 [3 4]]


In [18]:
#Exampe 5
import numpy.matlib
import numpy as np

k = np.asmatrix(j)
print(k)

[[1 2]
 [3 4]]
