In [4]:
import numpy as np
import tensorflow as tf

In [7]:
tf.__version__

'2.1.0'

In [5]:
hello = tf.constant('Hello')
world = tf.constant('world')

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [8]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [9]:
 print(hello)

tf.Tensor(b'Hello', shape=(), dtype=string)


In [14]:
import tensorflow as tf
msg = tf.constant('Hello, TensorFlow!')
tf.print(msg)

Hello, TensorFlow!


In [15]:
var1 = tf.constant(10)
var2 = tf.constant(30)

In [16]:
var1+var2

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [17]:
tf.print(var1+var2)

40


In [18]:
const = tf.constant(10)

In [19]:
mat_1 = tf.fill((5,5),10)

In [20]:
tf.print(mat_1)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [21]:
zeros = tf.zeros((5,5))
tf.print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [22]:
onse = tf.ones((5,5))
tf.print(onse)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
random = tf.random.normal((4,4),mean=0,stddev=1.0)
tf.print(random)

[[2.4865427 -0.67746979 1.22009063 -0.783523917]
 [1.04202044 -1.20137715 -0.942586184 0.618592501]
 [-1.95835102 -0.695782304 1.12326729 0.606861293]
 [-0.199280351 0.647489786 0.331989 -0.0185290333]]


In [28]:
randu = tf.random.uniform((4,4),minval=0,maxval=1)
tf.print(randu)

[[0.345618844 0.0312966108 0.355348349 0.0688626766]
 [0.168608904 0.0458908081 0.556176424 0.339216828]
 [0.348530531 0.861472845 0.54772675 0.834301]
 [0.290722489 0.333434463 0.324534416 0.224316359]]


In [30]:
sess = tf.compat.v1.InteractiveSession

In [41]:
a = tf.constant([[1,2],[3,4]])
a.get_shape()

TensorShape([2, 2])

In [42]:
b = tf.constant([[10],[100]])
b.get_shape()

TensorShape([2, 1])

In [43]:
result = tf.matmul(a,b)

In [46]:
tf.print(result)

[[210]
 [430]]
