In [3]:
# Example 1
import numpy as np
a = np.array([1,2,3,])
print( a )

[1 2 3]


In [4]:
# More than one dimensions
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print( a )

[[1 2 3]
 [4 5 6]]


In [6]:
#Minimum dimensions
import numpy as np
a = np.array([1,2,3,4,5],ndmin=2)
print( a )

[[1 2 3 4 5]]


In [7]:
# dtype parameter
import numpy as np
a = np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]
