In [1]:
#numpy.dot()
import numpy.matlib
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [2]:
#numpy.vdot()
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.vdot(a,b))

130


In [3]:
#numpy.inner()
import numpy as np
print( np.inner(np.array([1,2,3]),np.array([0,1,0])) )

#Equqte to 1*0+2*1+3*0

2


In [5]:
#Multi dimensional array example
import numpy as np
a = np.array([[1,2],[3,4]])

print('Array a:')
print(a)
print('\n')

b = np.array([[11,12],[13,14]])
print('Array b:')
print(b)
print('\n')

print('Inner product:')
print(np.inner(a,b))

Array a:
[[1 2]
 [3 4]]


Array b:
[[11 12]
 [13 14]]


Inner product:
[[35 41]
 [81 95]]


In [6]:
#numpy.matmul
#For 2-D array, it is matrix multiplication
import numpy.matlib
import numpy as np

a = [[1,0],[0,1]]
b = [[4,1],[2,2]]

print(np.matmul(a,b))

[[4 1]
 [2 2]]


In [7]:
#2-D mixed with 1-D
import numpy.matlib
import numpy as np

a = [[1,0],[0,1]]
b = [1,2]

print( np.matmul(a,b) )
print( np.matmul(b,a) )

[1 2]
[1 2]


In [8]:
#one array having dimenstiona > 2
import numpy.matlib
import numpy as np

a = np.arange(8).reshape(2,2,2)
b = np.arange(4).reshape(2,2)

print(np.matmul(a,b))

[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


In [9]:
#Determinate
import numpy as np
print( np.linalg.det(a) )

[-2. -2.]


In [10]:
#example
import numpy as np
b = np.array([[6,1,1],[4,-2,5],[2,8,7]])

print(b)
print(np.linalg.det(b))
print(6*(-2*7-5*8)-1*(4*7-5*2)+1*(4*8 - -2*2))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


In [12]:
#numpy.linalg.solve()
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)

print(x)
print('\n')
print(y)
print('\n')
print( np.dot(x,y) )

[[1 2]
 [3 4]]


[[-2.   1. ]
 [ 1.5 -0.5]]


[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [14]:
#example 1
import numpy as np
a = np.array([[1,1,1],[0,2,5],[2,5,-1]])

print('Array a:')
print(a)
print('\n')

ainv = np.linalg.inv(a)
print(ainv)
print('\n')

print('Matrix B is:')
b = np.array([[6],[-4],[27]])
print(b)
print('\n')

print('compute A-1B:')

Array a:
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]


[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]


Matrix B is:
[[ 6]
 [-4]
 [27]]


compute A-1B:


In [ ]:
nmbvcbmnh