In [1]:
import numpy as np
nm = ('raju','anil','ravi','amar')
dv = ('f.y.','s.y.','s.y.','f.y.')

ind = np.lexsort((dv,nm))
print('Applying lexsort() function:')
print(ind)
print('\n')

print('Use this index to get sorted data:')
print(nm[i]+", "+dv[i] for i in ind )

Applying lexsort() function:
[3 1 0 2]


Use this index to get sorted data:
<generator object <genexpr> at 0x10e0547d0>


In [2]:
#numpy.argmax() and numpy.argmin()
import numpy as np
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

print('Our array is:')
print(a)
print('\n')

print('Applying argmax() function:')
print( np.argmax(a) )
print('\n')

print( 'Index of maximum number in flatteded array' )
print(a.flatten())
print('\n')

print('Array containing indices of maximum along axis 0:')
maxindex = np.argmax(a,axis=0)
print(maxindex)
print('\n')

print('Array containing indices of maximum along axis 1:')
maxindex = np.argmax(a,axis=1)
print(maxindex)
print('\n')

print('applying argmin() function:')
minindex=np.argmin(a)
print( minindex )
print('\n')

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying argmax() function:
7


Index of maximum number in flatteded array
[30 40 70 80 20 10 50 90 60]


Array containing indices of maximum along axis 0:
[1 2 0]


Array containing indices of maximum along axis 1:
[2 0 1]


applying argmin() function:
5




In [3]:
#numpy.nonzero()
import numpy as np
a = np.array([[30,20,0],[0,20,10],[50,0,60]])

print('Our array is:')
print(a)
print('\n')

print('Applying nonzero() function:')
print( np.nonzero(a) )

Our array is:
[[30 20  0]
 [ 0 20 10]
 [50  0 60]]


Applying nonzero() function:
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


In [4]:
#numpy.where()
import numpy as np
x = np.arange(9.).reshape(3,3)

print('Our array is:')
print(x)

print('Indices of elements>3')
y = np.where(x>3)
print(y)

print('Use these indices to get elements satisfying the condition')
print( x[y] )

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Indices of elements>3
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))
Use these indices to get elements satisfying the condition
[4. 5. 6. 7. 8.]


In [6]:
#Numpy.extract()
import numpy as np
x = np.arange(9.).reshape(3,3)

print('Our array is:')
print(x)
print('\n')

#define a condition
condition = np.mod(x,2) == 0
print('Element-wise value of condition')
print(condition)
print('\n')

print('Extract elements using condtion')
print(np.extract(condition,x))

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Element-wise value of condition
[[ True False  True]
 [False  True False]
 [ True False  True]]


Extract elements using condtion
[0. 2. 4. 6. 8.]


In [8]:
#numpy.ndarray.byteswap()
import numpy as np

a = np.array([1,256,8755],dtype=np.int16)
print('Our array is:')
print(a)
print('\n')

print('Representation of date in memeory in hexadecimal from:')
print(map(hex,a))
print('\n')

#byteswap() function swape in place by passign true paremeter
print('Applying byteswap() function:')
print( a.byteswap(True) )
print('In hexadecimal form:')
print(map(hex,a))

#we can see the bytes being swapped

Our array is:
[   1  256 8755]


Representation of date in memeory in hexadecimal from:


Applying byteswap() function:
[  256     1 13090]
In hexadecimal form:


In [11]:
#No Copy
import numpy as np

a = np.arange(6)
print('Our array is:')
print(a)
print('\n')

print('Applying id() function:')
print( id(a) )
print('\n')

print('a is assigned to b:')
b = a
print(b)
print('\n')

print('b ha ssam id():')
print( id(b) )
print('\n')

print('Chnage shape of b:')
b.shape = 2,3
print(b)
print('\n')

print('Shape of a also gets changed:')
print(a)

Our array is:
[0 1 2 3 4 5]


Applying id() function:
4553276352


a is assigned to b:
[0 1 2 3 4 5]


b ha ssam id():
4553276352


Chnage shape of b:
[[0 1 2]
 [3 4 5]]


Shape of a also gets changed:
[[0 1 2]
 [3 4 5]]


In [13]:
#views or Shallow Copy
import numpy as np

#To begin with, a is 3x2 array
a = np.arange(6).reshape(3,2)
print('Array a:')
print(a)
print('\n')

print('Create view of a:')
b = a.view()
print(b)
print('\n')

print('id() for both the arrays are differnet:')
print('id() of a:')
print(id(a))
print('\n')

print('id() of b:')
print(id(b))
print('\n')

#Change the shape of b. It does not change the shape of a
b.shape=2,3
print('Shape of b:')
print(b)
print('\n')

print('Shape of a:')
print(a)

Array a:
[[0 1]
 [2 3]
 [4 5]]


Create view of a:
[[0 1]
 [2 3]
 [4 5]]


id() for both the arrays are differnet:
id() of a:
4553225680


id() of b:
4553226080


Shape of b:
[[0 1 2]
 [3 4 5]]


Shape of a:
[[0 1]
 [2 3]
 [4 5]]


In [15]:
#Example
import numpy as np

a = np.array([[10,10],[2,2],[4,5]])
print('Our array is:')
print(a)
print('\n')

print('Create a slice:')
s=a[:,:2]
print(s)

Our array is:
[[10 10]
 [ 2  2]
 [ 4  5]]


Create a slice:
[[10 10]
 [ 2  2]
 [ 4  5]]


In [17]:
#Deep Copy
import numpy as np

a = np.array([[10,10],[2,3],[4,5]])
print('Array a is:')
print(a)
print('\n')

print('Create a deep copy of a:')
b = a.copy()
print('Array b is:')
print(b)
print('\n')

#b does not share any memory of a
print('Can we write b is a')
print( b is a )
print('\n')

print('Change the contente of b:')
b[0,0] = 100
print('Modified array b:')
print(b)
print('\n')

print('a remaains unchanged:')
print(a)

Array a is:
[[10 10]
 [ 2  3]
 [ 4  5]]


Create a deep copy of a:
Array b is:
[[10 10]
 [ 2  3]
 [ 4  5]]


Can we write b is a
False


Change the contente of b:
Modified array b:
[[100  10]
 [  2   3]
 [  4   5]]


a remaains unchanged:
[[10 10]
 [ 2  3]
 [ 4  5]]
