In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [21]:
data = pd.read_csv('50_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [22]:
#Real Data
real_x = data.iloc[:,0:4].values
real_y = data.iloc[:,4].values

In [23]:
#Label Encoder
le = LabelEncoder()
real_x[:,3] = le.fit_transform(real_x[:,3])
oneHE = OneHotEncoder(categories='auto')
real_x = oneHE.fit_transform(real_x).toarray()


In [24]:
real_x = real_x[:,1:]

In [25]:
#Split
training_x,test_x,training_y,test_y = train_test_split(real_x,real_y,test_size=0.2,random_state=0)


In [26]:
MLR = LinearRegression()
MLR.fit(training_x,training_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
pred_y = MLR.predict(test_x)
pred_y

array([108087.40943475,  94075.52935037, 103684.13111554, 109115.49885826,
       103344.82807584, 119826.12211671,  94325.09783199, 130700.8478805 ,
       108898.78755726, 103344.82807584])

In [28]:
test_y

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [29]:
real_x = np.append(arr=np.ones((50,1)).astype(int),values=real_x,axis=1)


In [30]:
x_opt = real_x[:,[0,1,2,3,4,5]]

In [31]:
reg_OLS = sm.OLS(endog=real_y,exog=x_opt).fit()

In [32]:
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.203
Model:                            OLS   Adj. R-squared:                  0.113
Method:                 Least Squares   F-statistic:                     2.244
Date:                Fri, 01 May 2020   Prob (F-statistic):             0.0665
Time:                        14:52:40   Log-Likelihood:                -594.98
No. Observations:                  50   AIC:                             1202.
Df Residuals:                      44   BIC:                             1213.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.178e+05   5659.867     20.808      0.000    1.06e+05    1.29e+05
x1         -8.209e+04   3.84e+04     -2.139      0.038   -1.59e+05   -4730.369
x2         -5.284e+04   3.84e+04     -1.377      0.176    -1.3e+05    2.45e+04
x3         -6.828e+04   3.84e+04     -1.779      0.082   -1.46e+05    9086.971
x4         -4.801e+04   3.84e+04     -1.251      0.218   -1.25e+05    2.94e+04
x5         -3.654e+04   3.84e+04     -0.952      0.346   -1.14e+05    4.08e+04
==============================================================================
Omnibus:                        1.590   Durbin-Watson:                   0.512
Prob(Omnibus):                  0.452   Jarque-Bera (JB):                0.795
Skew:                          -0.059   Prob(JB):                        0.672
Kurtosis:                       3.606   Cond. No.                         7.47
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [33]:
x_opt = real_x[:,[0,1,2,3,4,5]]
reg_OLS = sm.OLS(endog=real_y,exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.203
Model:                            OLS   Adj. R-squared:                  0.113
Method:                 Least Squares   F-statistic:                     2.244
Date:                Fri, 01 May 2020   Prob (F-statistic):             0.0665
Time:                        14:55:02   Log-Likelihood:                -594.98
No. Observations:                  50   AIC:                             1202.
Df Residuals:                      44   BIC:                             1213.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.178e+05   5659.867     20.808      0.000    1.06e+05    1.29e+05
x1         -8.209e+04   3.84e+04     -2.139      0.038   -1.59e+05   -4730.369
x2         -5.284e+04   3.84e+04     -1.377      0.176    -1.3e+05    2.45e+04
x3         -6.828e+04   3.84e+04     -1.779      0.082   -1.46e+05    9086.971
x4         -4.801e+04   3.84e+04     -1.251      0.218   -1.25e+05    2.94e+04
x5         -3.654e+04   3.84e+04     -0.952      0.346   -1.14e+05    4.08e+04
==============================================================================
Omnibus:                        1.590   Durbin-Watson:                   0.512
Prob(Omnibus):                  0.452   Jarque-Bera (JB):                0.795
Skew:                          -0.059   Prob(JB):                        0.672
Kurtosis:                       3.606   Cond. No.                         7.47
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [34]:
x_opt = real_x[:,[0,1,2,3,4]]
reg_OLS = sm.OLS(endog=real_y,exog=x_opt).fit()
reg_OLS.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.187
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     2.584
Date:                Fri, 01 May 2020   Prob (F-statistic):             0.0496
Time:                        14:56:33   Log-Likelihood:                -595.48
No. Observations:                  50   AIC:                             1201.
Df Residuals:                      45   BIC:                             1211.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.17e+05   5592.160     20.917      0.000    1.06e+05    1.28e+05
x1          -8.13e+04   3.83e+04     -2.121      0.039   -1.59e+05   -4083.603
x2         -5.205e+04   3.83e+04     -1.358      0.181   -1.29e+05    2.52e+04
x3         -6.748e+04   3.83e+04     -1.760      0.085   -1.45e+05    9733.737
x4         -4.721e+04   3.83e+04     -1.232      0.225   -1.24e+05       3e+04
==============================================================================
Omnibus:                        1.208   Durbin-Watson:                   0.460
Prob(Omnibus):                  0.547   Jarque-Bera (JB):                0.481
Skew:                          -0.012   Prob(JB):                        0.786
Kurtosis:                       3.480   Cond. No.                         7.38
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [35]:
x_opt = real_x[:,[0,1,2,3]]
reg_OLS = sm.OLS(endog=real_y,exog=x_opt).fit()
reg_OLS.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.159
Model:                            OLS   Adj. R-squared:                  0.105
Method:                 Least Squares   F-statistic:                     2.908
Date:                Fri, 01 May 2020   Prob (F-statistic):             0.0445
Time:                        14:57:15   Log-Likelihood:                -596.31
No. Observations:                  50   AIC:                             1201.
Df Residuals:                      46   BIC:                             1208.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.16e+05   5563.332     20.845      0.000    1.05e+05    1.27e+05
x1          -8.03e+04   3.85e+04     -2.083      0.043   -1.58e+05   -2710.722
x2         -5.104e+04   3.85e+04     -1.324      0.192   -1.29e+05    2.65e+04
x3         -6.648e+04   3.85e+04     -1.725      0.091   -1.44e+05    1.11e+04
==============================================================================
Omnibus:                        0.787   Durbin-Watson:                   0.365
Prob(Omnibus):                  0.675   Jarque-Bera (JB):                0.207
Skew:                           0.028   Prob(JB):                        0.902
Kurtosis:                       3.310   Cond. No.                         7.30
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [36]:
x_opt = real_x[:,[0,1,3]]
reg_OLS = sm.OLS(endog=real_y,exog=x_opt).fit()
reg_OLS.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.127
Model:                            OLS   Adj. R-squared:                  0.090
Method:                 Least Squares   F-statistic:                     3.430
Date:                Fri, 01 May 2020   Prob (F-statistic):             0.0407
Time:                        14:58:37   Log-Likelihood:                -597.25
No. Observations:                  50   AIC:                             1200.
Df Residuals:                      47   BIC:                             1206.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.149e+05   5549.041     20.707      0.000    1.04e+05    1.26e+05
x1         -7.923e+04   3.88e+04     -2.040      0.047   -1.57e+05   -1089.548
x2         -6.541e+04   3.88e+04     -1.684      0.099   -1.44e+05    1.27e+04
==============================================================================
Omnibus:                        0.458   Durbin-Watson:                   0.343
Prob(Omnibus):                  0.796   Jarque-Bera (JB):                0.074
Skew:                           0.061   Prob(JB):                        0.964
Kurtosis:                       3.144   Cond. No.                         7.22
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [40]:
x_opt = real_x[:,[0,1]]
reg_OLS = sm.OLS(endog=real_y,exog=x_opt).fit()

x_opt

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.]])

In [ ]:
training_x,test_x,training_y,test_y = train_test_split(real_x,real_y,test_size=0.2,random_state=0)