In [1]:
#convert lsit to ndarray
import numpy as np
x = [1,2,3]
a = np.asarray(x)

print(a)

[1 2 3]


In [5]:
#Example 2
#dtype is set
import numpy as np
x = [1,2,3]
a = np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [6]:
#ndarray from tuple
import numpy as np
x = (1,2,3)
a = np.asarray(x)
print(a)

[1 2 3]


In [7]:
#Example 4
#ndarray from list of toples
import numpy as np
x = [(1,2,3),(4,5)]
a = np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


In [18]:
import numpy as np
s = 'Hello World'
a = np.frombuffer(s,dtype='S1')
print(s)

TypeError: a bytes-like object is required, not 'str'

In [19]:
#Numpy.fromiter
# Example 6
#create lsit object using range function
import numpy as np
list = range(5)
print(list)

range(0, 5)


In [20]:
#Example7
#obtain iterator object from list
import numpy as np
list = range(5)
it = iter(list)

#use iterator to create ndarray
x = np.fromiter(it,dtype=float)
print(x)

[0. 1. 2. 3. 4.]
