In [3]:
#numpy.arange
import numpy as np
x = np.arange(2,50,2,dtype=float)
x

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48.])

In [5]:
#Example 2
import numpy as np

#dtype set
x = np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [11]:
#numpy.arange
import numpy as np
x = np.arange(2,15,dtype=complex)
print(x)

[ 2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j 10.+0.j
 11.+0.j 12.+0.j 13.+0.j 14.+0.j]


In [37]:
#numpy.linspace
import numpy as np
x = np.linspace(0,20,5,endpoint=True,dtype=float)
x

array([ 0.,  5., 10., 15., 20.])

In [46]:
#numpy.logspace
import numpy as np

# default base is 10
a = np.logspace(1.0,2.0,num=5,endpoint=True,base=2)
print(a)

[2.         2.37841423 2.82842712 3.36358566 4.        ]


In [52]:
#set base fo log space to 2
import numpy as np
a = np.logspace(1,10,num=10,base=2,dtype=int)
a

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])