In [2]:
#Example 7
import numpy as np

a = np.arange(0,60,5)
a = a.reshape(3,4)

print('First array is:')
print(a)
print('\n')

print('Second array is:')
b = np.array([1,2,3,4],dtype=int)
print(b)

print('\n')
print('Modified array is:')
for x,y in np.nditer([a,b]):
    print("%d:%d" %(x,y))

First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [3]:
#numpy.swapaxes
#Example 7
# It creates a 3 dimensional ndarray
import numpy as np
a = np.arange(8).reshape(2,2,2)

print('The orignal array:')
print(a)
print('\n')

#now swap numbers between axis 0( along depth ) and axis 2 ( along width )
print('the array after applying the wapaxes function')
print( np.swapaxes(a,2,0) )

The orignal array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


the array after applying the wapaxes function
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [4]:
#numpy.rollaxis 
#It creates 3 dimensional ndarray
import numpy as np
a = np.arange(8).reshape(2,2,2)

print('The original array:')
print(a)
print('\n')

#to roll axis-2 to axis-0 ( along width to along depth )
print( 'After applying rollaxis function:' )
print( np.rollaxis(a,2) )

#To roll axis 0 to 1 ( along with to height )
print('\n')
print('After applying rollaxis function:')
print( np.rollaxis(a,2,1) )



The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


After applying rollaxis function:
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


After applying rollaxis function:
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [5]:
#Example 9
import numpy as np

x = np.array([[1],[2],[3]])
y = np.array([4,5,6])

#tobroadcast x against y
b = np.broadcast(x,y)

#it has an iterator property, a tuple of iterators alons self's
print('broadcast x agains y:')
r,c = b.iters
print( r.next(),c.next() )
print( r.next(),c.next() )
print('\n')

#Shape attribute returns the shape of broadcast object
print( 'The shape of the broadcast object:' )
print( b.shape )
print('\n')

#to add x and y manually using broadcast
b = np.broadcast(x,y)
c = np.empty(b.shape)

print('Add x and y manually using broadcast:')
print(c.shape)
print('\n')

#same result obtained by Numpy's built in broadcasting support
print( 'The summation of x and y:' )
print(x+y)

broadcast x agains y:


AttributeError: 'numpy.flatiter' object has no attribute 'next'

In [6]:
#numpy.broadcast_to
import numpy as np
a = np.arange(4).reshape(1,4)

print('The original array:')
print(a)
print('\n')

print('After applying the broadcast_to fucntion:')
print( np.broadcast_to(a,(4,4)) )

The original array:
[[0 1 2 3]]


After applying the broadcast_to fucntion:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [7]:
#numpy.squeeze
import numpy as np
x = np.arange(9).reshape(1,3,3)

print('Array X:')
print(x)
print('\n')

y = np.squeeze(x)
print('Array Y:')
print(y)
print('\n')

print('The shapes of x and y array:')
print( x.shape,y.shape )

Array X:
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


Array Y:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


The shapes of x and y array:
(1, 3, 3) (3, 3)


In [10]:
#numpy.concatenate
import numpy as np
a = np.array([[1,2],[3,4]])

print('First array:')
print(a)
print('\n')

b = np.array([[5,6],[7,8]])
print('Second array:')
print(b)
print('\n')

#both the arrays are of same demensions
print('Joining the two arrays along axis 0:')
print( np.concatenate((a,b)) )
print('\n')

print('Joining the two array along axis 1:')
print( np.concatenate((a,b),axis=1) )

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#numpy.stack
