In [12]:
#Example 1
import numpy as np
a = np.arange(50)
s = slice(2,10,2)
print(a[s])

[2 4 6 8]


In [13]:
#Example 2
import numpy as np
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [17]:
#Example 5
import numpy as np
a = np.arange(10)
b = a[2]
print(b)

2


In [23]:
#Example 4
#Slice items starting from index
a = np.arange(10)
print( a[3:7] )

[3 4 5 6]


In [31]:
#Example 6
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print('\n')

#Slice items starting from index
print('Now we will slice the array the index a[1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


Now we will slice the array the index a[1:]
[[3 4 5]
 [4 5 6]]


In [36]:
#Example 7
#array to begin with
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print('Our array is:')
print(a)
print('\n')

#this returns arrray of items in the second column
print('The items in the second column are:')
print( a[...,1] )
print('\n')

#Now we will slice all items from the second row
print('The item in the second row are:')
print(a[1,...])
print('\n')

#Now we will slice all items form column 1 onwards
print('The items column 1 onwards are:')
print( a[...,1:3] )

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The item in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
