In [2]:
#Example 1
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
# more then one dimenstion
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [5]:
#minium dimensions
import numpy as np
a = np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [8]:
#dtype paramenter
import numpy as np
a = np.array([1,2,3],dtype=float)
print(a)

[1. 2. 3.]


In [9]:
#Numpy.flags
import numpy as np
x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [10]:
#numpy.empty
# Example 1
import numpy as np
x = np.empty([3,2],dtype=int)
print(x)

[[4607182418800017408                   0]
 [4611686018427387904                   0]
 [4613937818241073152                   0]]


In [11]:
#numpy.zeros
#array of five zeros.Default dtype is float
import numpy as np
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [12]:
#Example 3
import numpy as np
x = np.zeros((5),dtype=np.int)
print(x)

[0 0 0 0 0]


In [13]:
#Example 4
import numpy as np
x = np.zeros((2,2),dtype=[('x','i4'),('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [14]:
#numpy.ones
#array of five ones. Default dtype is float
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [16]:
#Example 6
import numpy as np
x = np.ones([3,5],dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
