In [2]:
import sys
import numpy as np


print('python:{}'.format(sys.version))
print('NumPy:{}'.format(np.__version__))

python:3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
NumPy:1.18.1


In [4]:
#Defining a scalar
x = 6
x

6

In [5]:
#define a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

In [6]:
print('Vector Dimensions:{}'.format(x.shape))
print('Vector Size:{}'.format(x.size))

Vector Dimensions:(3,)
Vector Size:3


In [10]:
# Defining a matrix
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
print('Matrix dimensiions:{}'.format(x.shape))
print('Matrix size:{}'.format(x.size))

Matrix dimensiions:(3, 3)
Matrix size:9


In [13]:
#Define a matrix if a give dimension
x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
print('Matrix dimensiions:{}'.format(x.shape))
print('Matrix size:{}'.format(x.size))

Matrix dimensiions:(10, 10)
Matrix size:100


In [16]:
x = np.ones((3,3,3,3))
x

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [17]:
print('Tensor dimensiions:{}'.format(x.shape))
print('Tensor size:{}'.format(x.size))

Tensor dimensiions:(3, 3, 3, 3)
Tensor size:81


In [18]:
#Indexing 
A = np.ones((5,5),dtype=np.int)
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# Indexing stat at o
A[0,1] = 2
A

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
A[1,0] = 3
A

array([[1, 2, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
A[:,:] =5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [23]:
# For high dimensions , simply add an index
A = np.ones((5,5,5),dtype=np.int)

# Assing first row as new value
A[:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [24]:
# Matricx operations
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2),dtype=np.int)

In [25]:
A

matrix([[1, 2],
        [3, 4]])

In [26]:
B

array([[1, 1],
       [1, 1]])

In [27]:
# Element wise sum
C = A + B
C

matrix([[2, 3],
        [4, 5]])

In [28]:
# Element wise subtraction
C = A-B
C

matrix([[0, 1],
        [2, 3]])

In [29]:
# Matrix multiplication
C = A*B
C

matrix([[3, 3],
        [7, 7]])

In [30]:
# The matrix tranpose
A = np.array(range(9))
A = A.reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [32]:
C = B.T
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
A = np.array(range(10))
A = A.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
B = A.T
B

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [35]:
print( B.shape )
print( A.shape )

(5, 2)
(2, 5)


In [38]:
# Tensor
A = np.ones((3,3,3,3,3,3,3,3,3,3))

In [39]:
print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
