In [12]:
#divide()
import numpy as np
a = np.arange(9,dtype=np.float_).reshape(3,3)

print('First array:')
print(a)
print('\n')

print('Second array:')
b = np.array([10,10,10])
print(b)
print('\n')

print('Add the two arrays:')
print(np.add(a,b))
print('\n')

print('Subtract the two arrays:')
print( np.subtract(a,b) )
print('\n')

print('Multiply the two arrays:')
print(np.multiply(a,b))
print('\n')

print('Divide the two arrays:')
print(np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [13]:
#numpy.reciprocal
import numpy as np
a = np.array([0.25,1.33,1,0,100])

print('Our array is:')
print(a)
print('\n')

print('After applying reciprocal function:')
print(np.reciprocal(a))
print('\n')

b = np.array([100],dtype=int)
print('The second array is:')
print(b)
print('\n')

print('After applyg reciprocal function:')
print(np.reciprocal(b))

Our array is:
[  0.25   1.33   1.     0.   100.  ]


After applying reciprocal function:
[4.        0.7518797 1.              inf 0.01     ]


The second array is:
[100]


After applyg reciprocal function:
[0]


/Users/chitranjan/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in reciprocal
  # Remove the CWD from sys.path while we load stuff.


In [14]:
#numpy.power()
import numpy as np

a = np.array([10,100,1000])

print('Our array is:')
print(a)
print('\n')

print('Applying power function:')
print( np.power(a,2) )
print('\n')

print('Second array:')
b = np.array([1,2,3])
print(b)
print('\n')

print('Applying power function again:')
print(np.power(a,b))

Our array is:
[  10  100 1000]


Applying power function:
[    100   10000 1000000]


Second array:
[1 2 3]


Applying power function again:
[        10      10000 1000000000]


In [16]:
#numpy.mod()
import numpy as np

a = np.array([10,20,30])
b = np.array([3,5,7])

print('First array:')
print(a)
print('\n')

print('Second array:')
print(b)
print('\n')

print('Applying mod() function:')
print( np.mod(a,b) )
print('\n')

print('Applying remainder()  function:')
print(np.remainder(a,b))

First array:
[10 20 30]


Second array:
[3 5 7]


Applying mod() function:
[1 0 2]


Applying remainder()  function:
[1 0 2]
