In [3]:
import numpy as np

a = np.arange(12).reshape(3,4)
print('First array:')
print(a)
print('\n')

print('Array flattened before delete operation as axis not used:')
print(np.delete(a,5))
print('\n')

print('Column 2 deleted:')
print(np.delete(a,2,axis=1))
print('\n')

print('A slice containing alternate values from array deleted:')
a = np.array([1,2,3,4,5,6,7,8,9,10])
print( np.delete(a,np.s_[::2]) )

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array flattened before delete operation as axis not used:
[ 0  1  2  3  4  6  7  8  9 10 11]


Column 2 deleted:
[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]


A slice containing alternate values from array deleted:
[ 2  4  6  8 10]


In [4]:
#Example 22
a = np.array([5,2,6,2,7,5,6,8,2,9])

print('First array:')
print(a)
print('\n')

print('Unique values of first array:')
u = np.unique(a)
print(u)
print('\n')

print('Unique array and indices array:')
u,indices = np.unique(a,return_index=True)
print(indices)
print('\n')

print('We can see each number corresponds to index in original array:')
print(a)
print('\n')

print('Indices of unique array:')
u,indices = np.unique(a,return_inverse=True)
print(u)
print('\n')
print('Indices are:')
print('Indices')
print('\n')

print('Reconstruct the original array using indices:')
print(u[indices])
print('\n')

print('Return the count of repetitions of unique elements:')
u,indices = np.unique(a,return_counts=True)
print(u)
print(indices)

First array:
[5 2 6 2 7 5 6 8 2 9]


Unique values of first array:
[2 5 6 7 8 9]


Unique array and indices array:
[1 0 2 4 7 9]


We can see each number corresponds to index in original array:
[5 2 6 2 7 5 6 8 2 9]


Indices of unique array:
[2 5 6 7 8 9]


Indices are:
Indices


Reconstruct the original array using indices:
[5 2 6 2 7 5 6 8 2 9]


Return the count of repetitions of unique elements:
[2 5 6 7 8 9]
[3 2 2 1 1 1]
