In [3]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print('First array:')
print(a)
print('\n')

print('Axis parameter not passed. the input array is flatted before insertion')
print( np.insert(a,3,[11,12]) )
print('\n')

print('Axis parameter passed. The values array is broadcast to match input array.')
print('Broadcast along axis 0:')
print( np.insert(a,1,[11],axis=0) )
print('\n')

print('Broadcast along axis 1:')
print( np.insert(a,1,11,axis=1) )

First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed. the input array is flatted before insertion
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast along axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [4]:
#numpy.delete
import numpy as np

a = np.arange(12).reshape(3,4)

print('First array:')
print(a)
print('\n')

print('Array flattends before delete operation as axis not user:')
print( np.delete(a,5) )
print('\n')

print('Column 2 deleted:')
print( np.delete(a,1,axis=1) )
print('\n')

print('A alice containing alternate values from array deleted:')
a = np.array([1,2,3,4,5,6,7,8,9,10])

print( np.delete(a,np.s_[::2]) )

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array flattends before delete operation as axis not user:
[ 0  1  2  3  4  6  7  8  9 10 11]


Column 2 deleted:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


A alice containing alternate values from array deleted:
[ 2  4  6  8 10]


In [7]:
# Numpy.unique

import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
print 'First array:'
print a
print '\n'
print 'Unique values of first array:' u = np.unique(a)
print u
print '\n'
print 'Unique array and Indices array:' u,indices=np.unique(a, return_index=True) print indices
print '\n'
print 'We can see each number corresponds to index in original array:' print a
print '\n'
print 'Indices of unique array:' u,indices=np.unique(a,return_inverse=True) print u
print '\n'
print 'Indices are:'
print indices
print '\n'
print 'Reconstruct the original array using indices:' print u[indices]
print '\n'
print 'Return the count of repetitions of unique elements:' u,indices=np.unique(a,return_counts=True)
print u
print(indices)

SyntaxError: Missing parentheses in call to 'print'. Did you mean print('First array:')? (<ipython-input-7-67b8b69d87fa>, line 5)