In [2]:
#Example 4
import numpy as np
a = np.arange(8).reshape(2,4)
print('The original array is:')
print(a)
print('\n')


print('After applying revel function:')
print (a.ravel())

print('\n')
print('applying revel function in F-style ordering:')
print(a.ravel(order='F'))

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


After applying revel function:
[0 1 2 3 4 5 6 7]


applying revel function in F-style ordering:
[0 4 1 5 2 6 3 7]
