In [1]:
import numpy as np
a = np.array([[1,2],[3,4]])

print('First Array')
print(a)
print('\n')

b = np.array([[5,6],[7,8]])
print('Second Array:')
print(b)
print('\n')

print('Stack the two arrays along axis 0:')
print( np.stack((a,b),0) )
print('\n')

print('Stack the two arrays along axis 1:')
print(np.stack((a,b),1))

First Array
[[1 2]
 [3 4]]


Second Array:
[[5 6]
 [7 8]]


Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [2]:
#numpy.hstack and numpy.vstack
import numpy as np

a = np.array([[1,2],[3,4]])
print(a)
print('\n')

b = np.array([[5,6],[7,8]])
print('Second array:')
print(b)
print('\n')

print('Horizontal stacking:')
c = np.hstack((a,b))
print(c)
print('\n')

print('Vertical stacking:')
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]


Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
#numpy.split
import numpy as np
a = np.arange(8)

print('First array:')
print(a)
print('\n')

print('Split the array is 3 equal-sized subarrays:')
b = np.split(a,4)
print(b)
print('\n')

print('Split the array at positions indicated in 1-D array:')
b = np.split(a,[4,7])
print(b)

First array:
[0 1 2 3 4 5 6 7]


Split the array is 3 equal-sized subarrays:
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]


Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7])]


In [7]:
#numpy.hsplit and numpy.vsplit
import numpy as np

a = np.arange(16).reshape(4,4)
print('First array:')
print(a)
print('\n')

print('Horizontal splitting:')
b = np.hsplit(a,2)
print(b)
print('\n')

print('Vertical splitting:')
b = np.vsplit(a,2)
print(b)

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [8]:
#numpy.resize
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print('First array:')
print(a)
print('\n')

print('The shape of first arrray:')
print(a.shape)
print('\n')

b = np.resize(a,(3,2))
print('Second array:')
print(b)
print('\n')

print('The shape of second array:')
print( b.shape )
print('\n')

#Observe that first row of a is repeated in b since size is bigger
print('Resize the second array:')
b = np.resize(a,(3,3))
print(b)

First array:
[[1 2 3]
 [4 5 6]]


The shape of first arrray:
(2, 3)


Second array:
[[1 2]
 [3 4]
 [5 6]]


The shape of second array:
(3, 2)


Resize the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [13]:
#numpy.append
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print('First array:')
print(a)
print('\n')

print('Append elements to array:')
print(np.append(a,[7,8,9]))
print('\n')

print('Append elements along axis 0:')
print(np.append(a,[[7,8,9]],axis=0))
print('\n')

print('Append elements along axis 1:')
print( np.append(a,[[5,5,5],[7,8,9]],axis=1) )

First array:
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [14]:
#numpy.insert
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
print('First array:')
print(a)
print('\n')

 print('Axis parameter not passed.The input array is flattened before')
print(np.insert(a,3,[11,12]))
print('\n')

print('Axis parameter passed. The values array is broadcast to match input array.')
print('Broadcast along axis 0:')
print(np.insert(a,1,[11],axis=0))
print('\n')

print('Broadcast along axis 1:')
print( np.insert(a,1,11,axis=1) )

First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed.The input array is flattened before
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast along axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]
