In [1]:
#numpy.sort()
import numpy as np
a = np.array([[3,7],[9,1]])

print('Our array is:')
print(a)
print('\n')

print('Applying sort() function:')
print(np.sort(a))
print('\n')

#Order parameter in sort function
dt = np.dtype([('name','S10'),('age','int')])
a = np.array([("raju",21),("anil",25),('Ravi',17),("amar",27)],dtype=dt)

print('Our array is:')
print(a)
print('\n')

print('Order by name:')
print( np.sort(a,order='name') )

Our array is:
[[3 7]
 [9 1]]


Applying sort() function:
[[3 7]
 [1 9]]


Our array is:
[(b'raju', 21) (b'anil', 25) (b'Ravi', 17) (b'amar', 27)]


Order by name:
[(b'Ravi', 17) (b'amar', 27) (b'anil', 25) (b'raju', 21)]


In [2]:
#numpy.argsort()
import numpy as np

x = np.array([3,1,2])

print('Our array is:')
print(x)
print('\n')

print('Applying argsort() to x:')
y = np.argsort(x)
print(y)
print('\n')

print('Reconstruct original array in sorted order:')
print(i in y):
    print( x[i] )

SyntaxError: invalid syntax (<ipython-input-2-9fbdcb698ccb>, line 16)

In [4]:
#numpy.lexsort()
import numpy as np

nm = ('raju','anil','ravi','amar')
dv = ('f.y.','s.y.','s.y.','f.y.')

ind = np.lexsort((dv,nm))
print('Applying lexsort() function:')
print(ind)
print('\n')

print('Use this index to get sorted data:')
print( [nm[i]+","+dv[i] for i in ind] )

Applying lexsort() function:
[3 1 0 2]


Use this index to get sorted data:
['amar,f.y.', 'anil,s.y.', 'raju,f.y.', 'ravi,s.y.']


In [5]:
#numpy.nonzero()
import numpy as np

a = np.array([[30,40,0],[0,20,10],[50,0,60]])
print('Our array is:')
print(a)
print('\n')

print('Applying nonzero() function:')
print(np.nonzero(a))

Our array is:
[[30 40  0]
 [ 0 20 10]
 [50  0 60]]


Applying nonzero() function:
(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))


In [7]:
#numpy.where()
import numpy as np

x = np.arange(9).reshape(3,3)
print('Our array is:')
print(x)
print('\n')

print('Indices of elements > 3')
y = np.where(x>3)
print(y)
print('\n')

print('Use these indices to get elements satisfiying the condtion')
print(x[y])

Our array is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Indices of elements > 3
(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))


Use these indices to get elements satisfiying the condtion
[4 5 6 7 8]


In [8]:
#numpy.extract()
import numpy as np

x = np.arange(9).reshape(3,3)
print('Our array is:')
print(x)

#Define a condtion
condition = np.mod(x,2)==0
print('Element wise value of condtion')
print(condition)

#Define a condition
condition = np.mod(x,y) == 0
print('Element wise value of condtion')
print(condition)

print('Extract elements using condition')
print(np.extract(condition,x))


Our array is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Element wise value of condtion
[[ True False  True]
 [False  True False]
 [ True False  True]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,5) 

In [10]:
#numpy.extract()
import numpy as np
x = np.arange(9).reshape(3,3)

print('Our array is:')
print(x)
print('\n')

#define a condition
condition = np.mod(x,2) == 2
print('Element wise value of condition')
print(condition)
print('\n')

print('Extract elements using condition')
print(np.extract(condition,x))

Our array is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Element wise value of condition
[[False False False]
 [False False False]
 [False False False]]


Extract elements using condition
[]
