SyntaxError: invalid syntax (<ipython-input-2-bfaaabe48ff8>, line 4)

In [5]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

print('Our array is:')
print(a)
print('\n')

print('Applying amin() function:')
print( np.amin(a,1) )
print('\n')

print('Applying amin() function again:')
print(np.amin(a,0))
print('\n')

print('Applying amax() function:')
print( np.amax(a) )
print('\n')

print('Applying amax() function again:')
print( np.amax(a,axis=0) )

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
[3 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]


In [7]:
#numpy.ptp()
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

print('Our array is:')
print(a)
print('\n')

print('Applying plt() function:')
print( np.ptp(a) )
print('\n')

print('Applying ptp() function along axis 1:')
print( np.ptp(a,axis=1) )
print('\n')

print( 'Applying ptp() function along axis 0:' )
print( np.ptp(a,axis=0) )

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying plt() function:
7


Applying ptp() function along axis 1:
[4 5 7]


Applying ptp() function along axis 0:
[6 3 6]


In [8]:
#numpy.percentile()
import numpy as np

a = np.array([[30,40,70],[80,20,10],[50,90,60]])
print('Our array is:')
print(a)
print('\n')

print('Applying percentile() function:')
print( np.percentile(a,50) )
print('\n')

print('Applying percentile() function along axis 0:')
print( np.percentile(a,50,axis=0) )

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying percentile() function:
50.0


Applying percentile() function along axis 0:
[50. 40. 60.]


In [9]:
#Numpy.median()
import numpy as np
a = np.array([[30,65,70],[80,95,10],[50,90,60]])

print('Our array is:')
print(a)
print('\n')

print('Applying median() function:')
print(np.median(a))
print('\n')

print('Applying median() function along axis 0:')
print( np.median(a,axis=0) )
print('\n')

print('Applying median() function along axis 1: ')
print( np.median(a,axis=1) )

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


Applying median() function:
65.0


Applying median() function along axis 0:
[50. 90. 60.]


Applying median() function along axis 1: 
[65. 80. 60.]


In [11]:
#Numpy.mean()
import numpy as np

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:')
print(a)
print('\n')

print('Applying mean() function:')
print( np.mean(a) )
print('\n')

print('Applying mean() function along axis 0:')
print( np.mean(a,axis=0) )
print('\n')

print( 'applying mean() function along axis 1:' )
print( np.mean(a,axis=1) )

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function:
3.6666666666666665


Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


applying mean() function along axis 1:
[2. 4. 5.]


In [13]:
#numpy.average()
import numpy as np

a = np.array([1,2,3,4])
print('Our array is:')
print(a)
print('\n')

print('Applying average() function:')
print( np.average(a) )
print('\n')

#this is same as mean when weight is not specified
wts=np.array([4,3,2,1])
print('Applying average() function again:')
print( np.average(a,weights=wts) )
print('\n')

#Returns the sum of weights, if the returned paramenter is set true.
print('Sum of weights')
print(np.average([1,2,3,4],weights=[4,3,2,1],returned=True))

Our array is:
[1 2 3 4]


Applying average() function:
2.5


Applying average() function again:
2.0


Sum of weights
(2.0, 10.0)


SyntaxError: invalid syntax (<ipython-input-16-acfbbed12d7c>, line 2)

In [17]:
#Standard Deviation
import numpy as np
print( np.std([1,2,3,4]) )

1.118033988749895


In [18]:
#Variance
import numpy as np
print( np.var([1,2,3,4]) )

1.25


In [20]:
#numpy.sort()
import numpy as np

a = np.array([[3,7],[9,1]])
print(a)
print('\n')

print('Applying sort() function:')
print( np.sort(a) )
print('\n')

print('Sort along axis 0:')
print(np.sort(a,axis=0))
print('\n')

#Order parameter in sort function
dt = np.dtype([('name', 'S10'),('age', int)])
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype=dt)

print('Our array is:')
print(a)
print('\n')

print('Order by name:')
print(np.sort(a,order='name'))

[[3 7]
 [9 1]]


Applying sort() function:
[[3 7]
 [1 9]]


Sort along axis 0:
[[3 1]
 [9 7]]


Our array is:
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


Order by name:
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [21]:
#numpy.argsort()
import numpy as np
x = np.array([3,1,2])

print('Our array is:')
print(x)
print('\n')

print('Applying argsort() to x:')
y = np.argsort(x)
print(y)
print('\n')

print('Reconstruct original array in sorted order:')
print(x[y])
print('\n')

print('Reconstruct the original array using loop:')
for i in y:
    print(x[i])

Our array is:
[3 1 2]


Applying argsort() to x:
[1 2 0]


Reconstruct original array in sorted order:
[1 2 3]


Reconstruct the original array using loop:
1
2
3


In [25]:
#numpy.lexsort()
import numpy as np

nm = ('raju','anil','ravi','amar') 
dv = ('f.y.', 's.y.', 's.y.', 'f.y.')

ind = np.lexsort((dv,nm))
print('Applying lexort() function:')
print(ind)
print('\n')

print('Use this index to get sorted data:')
print ( [nm[i] + ", " + dv[i] for i in ind] )

Applying lexort() function:
[3 1 0 2]


Use this index to get sorted data:
['amar, f.y.', 'anil, s.y.', 'raju, f.y.', 'ravi, s.y.']
