In [1]:
#numpy.admin() and numpy.amax()
import numpy as np

a = np.array([[2,7,5],[8,4,3],[2,4,9]])

print('Our array is:')
print(a)
print('\n')

print('Applying amin()  functions:')
print( np.amin(a,1) )
print('\n')

print('Applying amin() function again:')
print( np.amin(a,0) )
print('\n')

print('Applying amax() function:')
print(np.amax(a))
print('\n')

print('Applying amax() function again:')
print( np.amax(a,axis=0) )

Our array is:
[[2 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin()  functions:
[2 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() function again:
[8 7 9]


In [2]:
#numpy.ptp()
import numpy as np

a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print('Our array is:')
print(a)
print('\n')

print('Applying ptp() function:')
print(np.ptp(a))
print('\n')

print('Applying ptp() function along axis 1:')
print( np.ptp(a,axis=1) )
print('\n')

print('Applying ptp() function along axis 0:')
print( np.ptp(a,axis=0) )

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying ptp() function:
7


Applying ptp() function along axis 1:
[4 5 7]


Applying ptp() function along axis 0:
[6 3 6]


In [4]:
#numpy.percentile()
import numpy as np

a = np.array([[30,40,70],[80,20,10],[50,90,60]])

print('Our array is:')
print(a)
print('\n')

print('Applying percentile() function:')
print( np.percentile(a,50) )
print('\n')

print('Applying percentile() function along axis 1:')
print( np.percentile(a,50,axis=1) )
print('\n')

print('Applying percentile() function along axis 0:')
print( np.percentile(a,50,axis=0) )

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying percentile() function:
50.0


Applying percentile() function along axis 1:
[40. 20. 60.]


Applying percentile() function along axis 0:
[50. 40. 60.]


In [ ]:
#numpy.median()
import numpy as np

a = np.array([[30,65,70],[80,95,10],[50,90,60]])

print('Our apply is:')
print(a)
print('\n')

print('')